fix
failed to load config from /vercel/path0/vite.config.js
error during build:
Error: The package "@esbuild/linux-x64" could not be found, and is needed by esbuild.
If you are installing esbuild with npm, make sure that you don't specify the
"--no-optional" or "--omit=optional" flags. The "optionalDependencies" feature
of "package.json" is used by esbuild to install the correct binary executable
for your current platform.
    at generateBinPath (/vercel/path0/node_modules/esbuild/lib/main.js:1754:15)
    at esbuildCommandAndArgs (/vercel/path0/node_modules/esbuild/lib/main.js:1824:33)
    at ensureServiceIsRunning (/vercel/path0/node_modules/esbuild/lib/main.js:1981:25)
    at build (/vercel/path0/node_modules/esbuild/lib/main.js:1880:26)
    at bundleConfigFile (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-glQox-ep.js:54476:24)
    at async bundleAndLoadConfigFile (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-glQox-ep.js:54460:19)
    at async loadConfigFromFile (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-glQox-ep.js:54423:44)
    at async resolveConfig (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-glQox-ep.js:53931:24)
    at async createBuilder (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-glQox-ep.js:51936:18)
    at async CAC.<anonymous> (file:///vercel/path0/node_modules/vite/dist/node/cli.js:859:23)
Error: Command "npm run build" exited with 1